apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aud-oct7-fb1-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/aud-oct7-fb1-1:17d9db2d9dede04d16404fc816c4949638e500c3@sha256:cced84fa1c138cccf7dd03d97a97fb5613e8acf40c27115231e7a42097264d60 # use pre-built to bootstrap 
          name: app-inference
