kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aud-oct7-fb1-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: aud-oct7-fb1-1-dsp-job
    namespace: aud-oct7-fb1-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aud-oct7-fb1-1-imagestream-job-role
