apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aud-oct7-fb1-1
  janus-idp.io/tekton: aud-oct7-fb1-1
  backstage.io/kubernetes-id: aud-oct7-fb1-1
  backstage.io/kubernetes-namespace: aud-oct7-fb1-1 
  app.kubernetes.io/part-of: aud-oct7-fb1-1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
